wrapper:
  config_file_name: avia.yaml
  lidar_topic: /cloud_registered_body
  imu_topic: /livox/imu
  odom_topic: /Odometry
  lidar_type: 0 # 0)avia

front_end:
  extrin:
    qx: 0
    qy: 0
    qz: 0
    qw: 1
    tx: 0
    ty: 0
    tz: 0
